config/routes.rb
Rails.application.routes.draw do
  resources :comixes, only: [:index, :show] do
    resources :pages, only: :show
  end
  root 'comixes#index'

  namespace :admin do
    resources :comixes
    resources :publishers
    resources :genres
    resources :pages
  end
end

app/models/comix.rb
class Comix < ActiveRecord::Base
  belongs_to :publisher
  has_and_belongs_to_many :genres
  has_many :pages
  accepts_nested_attributes_for :pages

  validates :title, :year, :language, :publisher_id, presence: true
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_and_belongs_to_many :comixes
end

app/models/page.rb
class Page < ActiveRecord::Base
  mount_uploader :page, PageUploader
  belongs_to :comix

  self.per_page = 1
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :comixes
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ActionController::Base
    protect_from_forgery

    layout 'admin'
  end
end

app/controllers/admin/comixes_controller.rb
module Admin
  class ComixesController < Admin::ApplicationController

    def index
      @comixes = Comix.all
    end

    def new
      @comix = Comix.new
      @pages = @comix.pages.build
    end

    def show
      @comix = Comix.find(params[:id])
      @pages = @comix.pages.all
    end

    def create
      @comix = Comix.new(comix_params)
      if @comix.save
        params[:pages]['page'].each do |page|
          @comix.pages.create!(page: page, comix_id: @comix.id)
        end

        redirect_to admin_comixes_path, message: 'Comix successfully created'
      else
        render :new
      end
    end

    def update
      @comix = Comix.find(params[:id])
      if @comix.update(comix_params)
        redirect_to admin_comixes_path, message: 'Comix successfully upddated'
      else
        render :edit
      end
    end

    def destroy
      @comix = Comix.find(params[:id])
      @comix.destroy
      redirect_to admin_comixes_path, message: 'Comix successfully destroyed'
    end

    def edit
      @comix = Comix.find(params[:id])
    end

    private

    def comix_params
      params.require(:comix).permit(:title, :year, :language, :publisher_id,  :pages_attributes, { genre_ids: [] })
    end

  end
end

app/controllers/admin/genres_controller.rb
module Admin
  class GenresController < Admin::ApplicationController

    def index
      @genres = Genre.all
    end

    def new
      @genre = Genre.new
    end

    def show
      @genre = Genre.find(params[:id])
    end

    def create
      @genre = Genre.new(genre_params)
      if @genre.save
        redirect_to admin_genres_path, message: 'Genre successfully created'
      else
        render :new
      end
    end

    def update
      @genre = Genre.find(params[:id])
      if @genre.update(genre_params)
        redirect_to admin_genres_path, message: 'Genre successfully upddated'
      else
        render :edit
      end
    end

    def destroy
      @genre = Genre.find(params[:id])
      @genre.destroy
      redirect_to admin_genres_path, message: 'Genre successfully destroyed'
    end

    def edit
      @genre = Genre.find(params[:id])
    end

    private

    def genre_params
      params.require(:genre).permit(:title)
    end

  end
end

app/controllers/admin/pages_controller.rb
module Admin
  class PagesController < ApplicationController
    before_action :set_page, only: [:show, :edit, :update, :destroy]

    def index
      @pages = Page.all
    end

    def show
    end

    def new
      @page = Page.new
    end

    def edit
    end

    def create
      @page = Page.new(page_params)

      respond_to do |format|
        if @page.save
          format.html { redirect_to @page, notice: 'Page was successfully created.' }
          format.json { render :show, status: :created, location: @page }
        else
          format.html { render :new }
          format.json { render json: @page.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @page.update(page_params)
          format.html { redirect_to @page, notice: 'Page was successfully updated.' }
          format.json { render :show, status: :ok, location: @page }
        else
          format.html { render :edit }
          format.json { render json: @page.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @page.destroy
      respond_to do |format|
        format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      def set_page
        @page = Page.find(params[:id])
      end

      def page_params
        params.require(:page).permit(:comix_id, :page)
      end
  end
end

app/controllers/admin/publishers_controller.rb
module Admin
  class PublishersController < Admin::ApplicationController

    def index
      @publishers = Publisher.all
    end

    def new
      @publisher = Publisher.new
    end

    def show
      @publisher = Publisher.find(params[:id])
    end

    def create
      @publisher = Publisher.new(publisher_params)
      if @publisher.save
        redirect_to admin_publishers_path, message: 'Publisher successfully created'
      else
        render :new
      end
    end

    def update
      @publisher = Publisher.find(params[:id])
      if @publisher.update(publisher_params)
        redirect_to admin_publishers_path, message: 'Publisher successfully upddated'
      else
        render :edit
      end
    end

    def destroy
      @publisher = Publisher.find(params[:id])
      @publisher.destroy
      redirect_to admin_publishers_path, message: 'Publisher successfully destroyed'
    end

    def edit
      @publisher = Publisher.find(params[:id])
    end

    private

    def publisher_params
      params.require(:publisher).permit(:name)
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comixes_controller.rb
class ComixesController < ApplicationController
  before_action :set_comix, only: [:show, :edit, :update, :destroy]

  def index
    @comixes = Comix.all
  end

  def show
    @pages = @comix.pages.paginate(:page => params[:page], :per_page => 1)
    current_page_id = params[:page] ? params[:page].to_i : 1
    @current_page = @comix.pages[current_page_id - 1].page_url
  end

  def new
    @comix = Comix.new
  end

  def edit
  end

  def create
    @comix = Comix.new(comix_params)

    respond_to do |format|
      if @comix.save
        redirect_to @comix, message: 'Comix was successfully created.'
      else
        render :new
      end
    end
  end

  def update
    respond_to do |format|
      if @comix.update(comix_params)
        redirect_to @comix, message: 'Comix was successfully updated.'
      else
        render :edit
      end
    end
  end

  def destroy
    @comix.destroy
    redirect_to comixes_url, message: 'Comix was successfully destroyed.'
  end

  private
    def set_comix
      @comix = Comix.find(params[:id])
    end

    def comix_params
      params[:comix]
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  def index
    @pages = Page.all
  end

  def show
  end

  def new
    @page = Page.new
  end

  def edit
  end

  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_page
      @page = Page.find(params[:id])
    end

    def page_params
      params[:page]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comixes_helper.rb
module ComixesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/application/_nav.html.slim
=> link_to 'Publishers', admin_publishers_path
=> link_to 'Comixes', admin_comixes_path
= link_to 'Genres', admin_genres_path

app/views/admin/comixes/_form.html.slim
= simple_form_for [:admin, @comix], html: { multipart: true } do |f|
  .col-sm-10
    = f.input :title
    = f.input :publisher_id, collection: Publisher.all.map { |p| [p.name, p.id] }, label: 'Publisher'
    = f.input :year
    = f.input :language
  .col-sm-2
    =f.collection_check_boxes :genre_ids, Genre.all, :id, :title, item_wrapper_class: 'checkbox'
  .col-sm-12
    = f.simple_fields_for :pages do |p|
      = p.input :page, input_html: { multiple: true, name: 'pages[page][]' }, as: :file, label: 'Pages'
    - @comix.pages.each do |p|
      = image_tag p.page_url, style: "width: 200px; height: 300px"

    p= f.button :submit, label: 'Save comix', class: 'btn btn-primary'

app/views/admin/comixes/edit.html.slim
h1 Editing comix
= link_to 'Show', admin_comix_path(@comix)

= render 'form'

app/views/admin/comixes/index.html.slim
h1 Comixes
= link_to 'New Comix', new_admin_comix_path

- @comixes.each do |comix|
  .comix
    h3= link_to comix.title, admin_comix_path(comix)
    => link_to '[Edit]', edit_admin_comix_path(comix)
    = link_to '[Destroy]', admin_comix_path(comix), data: {confirm: 'Are you sure?'}, method: :delete
    ul
      li= comix.language
      li= comix.publisher.name
      li= "#{comix.pages.count} страниц"

app/views/admin/comixes/new.html.slim
h1 New comix

== render 'form'

= link_to 'Back', comixes_path

app/views/admin/comixes/show.html.slim
p#notice = notice

h2= @comix.title
div= link_to 'Edit', edit_admin_comix_path(@comix)

- @pages.each do |p|
  = image_tag p.page_url, :style => "width: 200px; height: 300px;"

app/views/admin/genres/_form.html.slim
= simple_form_for [:admin, @genre] do |f|
  = f.input :title

  = f.submit 'Save'

app/views/admin/genres/edit.html.slim
h2= "Editing #{@genre.title}"

= render 'form'

app/views/admin/genres/index.html.slim
h1 Genres
= link_to '[New Genre]', new_admin_publisher_path
ul
- @genres.each do |genre|
  li
    => link_to genre.title, admin_genre_path(genre)
    => link_to '[Edit]', edit_admin_genre_path(genre)

app/views/admin/genres/new.html.slim
h2= "New Genre"

= render 'form'

app/views/admin/genres/show.html.slim
h2= @genre.title
= link_to '[Edit]', edit_admin_genre_path(@genre)

app/views/admin/publishers/_form.html.slim
= simple_form_for [:admin, @publisher] do |f|
  = f.input :name

  = f.submit 'Save'

app/views/admin/publishers/edit.html.slim
h2= "Editing #{@publisher.name}"

= render 'form'

app/views/admin/publishers/index.html.slim
h1 Publishers
= link_to '[New Publisher]', new_admin_publisher_path
ul
- @publishers.each do |publisher|
  li
    => link_to publisher.name, admin_publisher_path(publisher)
    => link_to '[Edit]', edit_admin_publisher_path(publisher)

app/views/admin/publishers/new.html.slim
h2 New publisher

= render 'form'

app/views/admin/publishers/show.html.slim
h2= @publisher.name
= link_to '[Edit]', edit_admin_publisher_path(@publisher)

app/views/comixes/index.html.slim
h1 Comixes
- @comixes.each do |comix|
  .comix
    h3= link_to comix.title, comix
    br
    = image_tag comix.pages.first.page_url, size: '200x300'

app/views/comixes/show.html.slim
h2= @comix.title
.publisher= @comix.publisher.name
.year= @comix.year
.language= @comix.language
.pages= "#{@pages.total_pages} страниц"

.text-center
  - if @pages.current_page < @pages.total_pages
    = link_to(image_tag(@current_page), "#{comix_path(@comix)}?page=#{@pages.current_page+1}")
  - else
    = image_tag @current_page

  = will_paginate @pages

app/views/layouts/admin.html.slim
doctype html
html
  head
    title= "ComixBro"
    = stylesheet_link_tag    "admin"
    = javascript_include_tag "admin"
    = csrf_meta_tags
  body
    .container
      .col-sm-3
        nav.mainmenu= render "nav"

    .container= yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title "ComixBro"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    .container= yield

app/views/pages/_form.html.slim
= simple_form_for(@page) do |f|
  = f.error_notification

  .form-inputs
    = f.input :comix_id
    = f.input :address

  .form-actions
    = f.button :submit

app/views/pages/edit.html.slim
h1 Editing page

== render 'form'

= link_to 'Show', @page
'|
= link_to 'Back', pages_path

app/views/pages/index.html.slim
h1 Listing pages

table
  thead
    tr
      th Comix
      th Address
      th
      th
      th

  tbody
    - @pages.each do |page|
      tr
        td = page.comix_id
        td = page.address
        td = link_to 'Show', page
        td = link_to 'Edit', edit_page_path(page)
        td = link_to 'Destroy', page, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Page', new_page_path

app/views/pages/new.html.slim
h1 New page

== render 'form'

= link_to 'Back', pages_path

app/views/pages/show.html.slim
h2= @page.comix.title